ingress:
  hosts:
    - host:
      paths:
        - path: /api
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path: /admin
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path: /static
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path: /django-rq
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path: /git
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path: /opencv
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path: /profiler
          pathType: "Prefix"
          service:
            name: backend-service
            port: 8080
        - path : /
          pathType: "Prefix"
          service:
            name: frontend-service
            port: 80

nuclio:
  enabled: true
  dashboards:
    containerBuildKind: "kaniko"
    nodePort: 31070
  registry:
    secretName: registry-credentials
    pushPullUrl: registry.hub.docker.com

analytics:
  enabled: true

traefik:
  logs:
    general:
      level: INFO
  ports:
    web:
      nodePort: 32180
    websecure:
      nodePort: 32143
  service:
    type: NodePort
    externalIPs:
      # - "192.168.49.2"